### PR TITLE
Master

### PR DESCRIPTION
**Pull request by enishoca**
Version 1.1.0
Major redesign 
- Compatible with pimatic v0.90+ 
- Supports pimatic auto-discovery
- Supports realtime pubnub subscriptions for status update
- Improved sync between Wink and Pimatic device statuses

### CODE REVIEW

**Comment by enishoca** [comment]
Would appreciate it if you can publish this to npm - thanks

**Comment by dgmltn** [comment]
Ok, sure, I'll invite you as a collaborator here and on npmjs for this project 👍

**Comment by enishoca** [comment]
Thank you
same as here enishoca
https://www.npmjs.com/~enishoca

**Comment by dgmltn** [comment]
Ok @enishoca , you're a collaborator on pimatic-wink now!

**Comment by enishoca** [comment]
Thank you

**Pull request merged**
