### PR TITLE
Suggested changes for pimatic 0.9 and bug fixture

### PR DESCRIPTION
**Pull request by mwittig**

### CODE REVIEW

**Comment by dgmltn** [comment]
I don't have the toolchain setup to test this, so I'll just trust you 👍

**Comment by mwittig** [comment]
You can test the code as is with pimatic 0.8 (apart from the destroy functions only used in pimatic 0.9). Another nice feature to add would be "auto-discovery" it this makes sense with "wink".

**Comment by dgmltn** [comment]
I just don't use pimatic anymore, and don't have it installed anywhere to test with.

**Comment by enishoca** [comment]
can you please push this change to npm - its still pulling the old version

**Comment by dgmltn** [comment]
@enishoca ok, v1.0.1 just published. @mwittig your node chi is much stronger than mine 😎

**Comment by enishoca** [comment]
@dgmltn are you still actively developing this?  I would like to make a couple of changes to the dimmer behaviour and also add auto-discovery.  I guess I can make the changes and make pull request to you

**Comment by dgmltn** [comment]
@enishoca No, I'm not actively developing it. I don't mind accepting PR's though.

**Comment by enishoca** [comment]
Thanks - I am new to coffeescript/javascript - can you please this piece of code to me - would appreciate it highly, what is it doing, and when is it executed 

```
       updateValue = =>
        if @config.interval > 0
          @downloadState().finally( =>
            @timerId = setTimeout(updateValue, @config.interval) 
          )
```

**Comment by dgmltn** [comment]
I'm also not comfortable with CoffeeScript... usually when I'm not sure what it's doing, I run it through a CoffeeScript->JavaScript converter. That might help.

**Comment by enishoca** [comment]
Hi - 
I have done a major revamp - added pubnub wink subscriptions for real time updates, add discovery and moved the device and token caches to config - I have checked in the code in my fork and you can look at the diff - I am not ready to make a PR yet.  I want to refactor the code a bit more, and cleanup the light_bulb dimmer behavior so it matches wink a little more closely.

Can you possibly make me a co-maintainer i.e., give me write access to github and npmjs. as per @mwittig suggestion here - https://forum.pimatic.org/topic/1921/major-update-to-wink-plugin-need-help-testing/6

**Comment by dgmltn** [comment]
Yeah, making you a co-maintainer for this project sounds like the right thing to do. What's your npmjs.com username?

**Pull request merged**
